# Generated by Django 4.0.5 on 2022-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='altitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='callsign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='on_ground',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
