# Generated by Django 4.0.5 on 2022-09-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_work', '0003_flight_destination_flight_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.AlterField(
            model_name='flight',
            name='callsign',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
