# Generated by Django 4.0.5 on 2022-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_work', '0005_originairports'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationAirports',
            fields=[
                ('airport', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('number_of_tracked_flights', models.IntegerField()),
            ],
        ),
    ]
